import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import java.io.IOException;
import java.io.InputStream;

/**
 * Created by webpigeon on 25/01/17.
 */
public class App {

    public static void main(String[] args) throws IOException {

        //create an input from a String
        ANTLRInputStream input = new ANTLRInputStream("y=sin(30)+9");

        //or from a file...
        //ANTLRInputStream input = new ANTLRInputStream(getFile("pow.txt"));

        //Create your lexer and parser
        //source code (lexer and parser) will be generated by antlr for you...
        CalculatorLexer lexer = new CalculatorLexer(input);
        CalculatorParser parser = new CalculatorParser(new CommonTokenStream(lexer));

        ParseTree tree = parser.equation();

        //print out the tree
        System.out.println("root: "+tree.getText());
        System.out.println("lhs: "+tree.getChild(0).getText()); //left hand side
        System.out.println("rhs: "+tree.getChild(2).getText()); //right hand side

        System.out.println(tree.getChild(2).getChild(0).getText());

        //print out the tree as a string
        System.out.println(tree.toStringTree(parser));

        //we can also walk though the tree
        //ParseTreeWalker walker = new ParseTreeWalker();
        CalculatorBaseListener listener = new MyCalculatorListener();
        ParseTreeWalker.DEFAULT.walk(listener, tree);
    }

    public static InputStream getFile(String filename) throws IOException {
        ClassLoader loader = App.class.getClassLoader();
        InputStream is = loader.getResourceAsStream(filename);
        if (is == null) {
            throw new IllegalArgumentException("cannot find requested file");
        }
        return is;
    }

}
